config/routes.rb
SocialNetwork::Application.routes.draw do

  get "microposts/new"

  resources :microposts, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :requests, :only => [:create, :destroy]
  resources :users do
    member do
      get :friends
			get :senders
			get :activate
		end
  end
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
	root :to => 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
      <p>There were problems with the following fields:</p>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<span id="show_microposts">
  <%= pluralize(@user.microposts.count, "micropost") %>
</span>
<% unless @feed_items.empty? %>
<table class="microposts" summary="User microposts">
  <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
</table>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item[1]),feed_item[1] %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item[1].name, feed_item[1]%>
    </span><br>
    <div class="content"><%= feed_item[0].content %></div>
    <%if feed_item[0].photo.original_filename %>
    <div class="image"><%= image_tag feed_item[0].photo.url(:medium) %></div>
    <div class="facepalm_image"><%= image_tag feed_item[0].photo.url%></div>
    <% end %>
    <%if feed_item[0].video_file_name %>
    <div id="player<%=feed_item[0].video_file_name%>">
      <%= video_tag feed_item[0].video.url,:controls=>"controls",:width=>350,:height=>300 %></div>
    </div>
    <% end %>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item[0].created_at) %> ago.
    </span>
    <% if current_user?(feed_item[0].user)||current_user.admin? %>
    <span class="delete_post">
        <%= link_to "delete",feed_item[0], :remote=>true ,:method => :delete, :controller => MicropostsController,
                    :confirm => "You really want it?",
                    :title => feed_item[0].content %>
    </span>
  <% end %>
  </td>

</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost, :remote => true  do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
      <%= f.text_area :content %>
      <%= f.hidden_field :from_id %>
      <%= f.hidden_field :user_id %>
      <%= f.file_field :photo %>
      <%= f.file_field :video %>
    </div>
    <div class="actions">
      <%= f.submit "Send" %>
      <%= link_to "Upload photo",{:id=>current_user.id}, :remote=>true ,:class=>"photo"%>
      <%= link_to "Upload video",{:id=>current_user.id}, :remote=>true,:class=>"video" %>
    </div>
<% end %>


<script type="text/javascript">
    $("table .micropost .delete_post a").live('click', function (e) {
        $(this).parent().parent().parent().remove();
    });
    $(".new_micropost div.actions a.photo").live('click', function (e) {
        $('#micropost_photo').attr('style','display:block;')
    });
    $(".new_micropost div.actions a.video").live('click', function (e) {
        $('#micropost_video').attr('style','display:block;')
    });
</script>

app/views/shared/_optional_fields.html.erb
<% if @user.data_of_burn? %>
  <div>
    <label>Date of birth:</label>
    <p class="property"><%= @user.data_of_burn %>  </p>
  </div>
<% end %>

<% if @user.sex? %>
    <div>
      <label>Sex:</label>
      <p class="property"><%= @user.sex %> </p>
    </div>            
<% end %>

<% if @user.phone? %>
    <div>
      <label>Phone number:</label>
      <p class="property"><%= @user.phone %> </p>
    </div>
<% end %>

<% if @user.city? %>
    <div>
      <label>City:</label>
      <p class="property"><%= @user.city %> </p>
    </div>
<% end %>

<% if @user.about? %>
    <div>
      <label>About myself:</label>
      <p class="property"><%= @user.about %></p>
    </div>
<% end %>

app/views/shared/_sender.html.erb
<li>
  <%= gravatar_for sender, :size => 30 %>
  <%= link_to sender.name, sender %>

  <%= form_for current_user.relationships.build(:friend_id=>sender.id) do |f| %>
      <%= f.hidden_field :friend_id %>
     <%= f.submit "Confirm" %>
  <% end %>

  <%= form_for current_user.requests.find_by_user_from_id(sender),
               :html => { :method => :delete } do |f| %>
    <%= f.submit "Refuse" %>
  <% end %>

</li>

app/views/shared/_sidebar.html.erb
<div class="for_sidebar">
  <div class="sidebar round">
    <%= render 'shared/user_info' %>
  </div>
  <% if @user.optional_fields?&&(current_user.friends?(@user)||(current_user==@user))%>
      <div class="sidebar round">
        <%= render 'shared/optional_fields' %>
      </div>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<div class="stats">

  <div>
    <b>
      <a href="<%= user_path(@user) %>">
       <span class="user_name">
        <%= @user.name %>
        </span>
      </a>
    </b>
  </div>

  <div class="status">
    <% if current_user==@user %>
        <% if @user.status? %>
            <% text=@user.status %>
        <% else %>
            <% text="Change status" %>
        <% end %>
        <%= link_to "#{text}",{:id=>current_user.id}, :remote=>true %>
    <% else %>
        <% if @user.status? %>
            <%= @user.status %>
        <% end %>
    <% end %>
  </div>

  <div>
    <%= gravatar_for @user, :size => 100 %>
  </div>

  <div class="info_friends">
    <%= render 'friendship_form' if signed_in? %>
  </div>
  <% if (current_user.friends?(@user))||(current_user==@user) %>
      <div>
        <a href="<%= friends_user_path(@user) %>">
          <span id="friends" class="stat">
            <%= pluralize(@user.friends.count, "friend") %>
          </span>
        </a>
      </div>
  <% end %>
  <% if current_user==@user %>
    <%= link_to "Statistics",{:id=>current_user.id},:remote=>true, :class=>"statistics" %>
  <% end %>

</div>