config/routes.rb
SocialNetwork::Application.routes.draw do

  get "microposts/new"

  resources :microposts, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :requests, :only => [:create, :destroy]
  resources :users do
    member do
      get :friends
			get :senders
			get :activate
		end
  end
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
	root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer style="clear:both; padding-top: 1em">
  <nav class="round">
    <ul>
      @Social network by Nastya Soroko
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
      <li class="name round">Social network</li>
      <% if signed_in? %>
          <% if current_user.admin? %>
          <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li><%= link_to "Friends", friends_user_path(current_user) %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <% if signed_in? %>
          <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'jquery-ui-rails', :media=>'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag 'application' %>

</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>
  <section class="round">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
    <% end %>
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

<script type="text/javascript">
$("div.status a").live('click', function (e) {
        var myStatus = $("div.status a").text();
        $("div.status a").hide();
        var myBox = $(document.createElement('textarea')).attr('style', 'width: 140px;word-wrap:break-word;height:40px;resize: none;margin-left:0;margin-bottom:0;').attr('value', myStatus);
        var myButton = $(document.createElement('button')).attr('style', 'width: 50px;').text("Save");
        $("div.status").append(myBox);
        $("div.status").append(myButton);
        $(myButton).live('click', function (e) {
            var newStatus = $(myBox).val();
            $(myButton).remove();
            $(myBox).remove();
            $("div.status a").text(newStatus);
            $("div.status a").show();
            $.ajax({
                url:'<%="http://localhost:3000/users/#{@user.id}"%>',
                type:"put",
                dataType:"json",
                data:{status:newStatus}
            });
        });
    });
</script>